services:
    laravel:
        build:
            context: './docker/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: '8.3/app-laravel'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8081:80'
            - '5173'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    swoole-octane:
        build:
            context: './docker/8.3-octane'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: '8.3/app-laravel-octane'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8082:80'
            - '5174'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    fpm:
        build:
            context: './docker/8.3-fpm'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: '8.3/app-fpm'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8083:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    nginx:
        image: nginx:1.25-alpine
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8123:80"
            - "8124:8080"
        depends_on:
            - fpm
            - laravel
            - swoole-octane
    wrk:
        container_name: "benchmark_tool"
        image: williamyeh/wrk
        volumes:
            - ./docker/bench/bench.sh:/app/bench.sh
        working_dir: /app
        entrypoint: /app/bench.sh
        depends_on:
            - fpm
            - laravel
            - swoole-octane
        restart: no
networks:
    sail:
        driver: bridge
